### ISSUE TITLE
Image compression is very severe by default

### ISSUE THREAD

**Issue by wgx** [ehowey/gatsby-starter-catalyst-helium#1]
How do I change the default image compression level (50) to something more generous?

I tried:

```json
    resolve: `gatsby-plugin-sharp`,
    options: {
      defaultQuality: 90,
    },
```

But no luck.

**Comment by ehowey** [comment]
Hey Will - thanks for this report.  I haven't had to adapt this yet but having said this I can definetly see why this would be a problem.  I am going to open an issue on the main repo and track the PR there.  I _think_ it should be a quick addition to the api similar to how you can specify the width for remark images.
